name: Validate PR for githubindia.com website
on:
  pull_request:
    branches:
      - main
    paths:
      - "website/**"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Checkout PR branch
        uses: dawidd6/action-checkout-pr@v1
        with:
          pr: ${{ github.event.number }}
      - name: Check format of yaml file
        id: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          strict: true
          file_or_dir: website/**/*.yml
          config_data: |
            extends: default
            rules:
              empty-lines:
                max: 1
              hyphens:
                max-spaces-after: 1
              indentation:
                spaces: consistent
                indent-sequences: true
                check-multi-line-strings: false
              new-lines:
                type: unix
              trailing-spaces: enable
              colons:
                max-spaces-before: 0
                max-spaces-after: 1
              empty-values:
                forbid-in-block-mappings: true
              key-duplicates: false
            format: github
  validate:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Checkout PR branch
        uses: dawidd6/action-checkout-pr@v1
        with:
          pr: ${{ github.event.number }}
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: ./india-main
          token: ${{ secrets.PAT }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Validate PR
        run: |
          gem install octokit
          ruby india-main/script/website-pr-validation.rb
        env:
          PR_ID: ${{ github.event.number }}
          PAT: ${{ secrets.PAT }}
          INDIA_REPO_NWO: ${{ secrets.INDIA_REPO_NWO }}
